### PR TITLE
Add extension discovery section

### PR DESCRIPTION
**Pull request by vi-nastya**
This PR adds ecosystem top-level section with `Discovery` and `Bundle builder` pages.

Deployed: https://mdr-ci.staging.k6.io/docs/refs/pull/274/merge/ecosystem/ 

**TODO**
- [x] Add discovery page description
- [ ] Add categories for extension data
- [x] Add support for custom extension image

### CODE REVIEW

**Comment by ppcano** [comment]
@simskij As part of this PR, I think:

- we should remove the current [Extensions section on the Integrations page](https://mdr-ci.staging.k6.io/docs/refs/pull/274/merge/integrations/#k6-extensions). Optionally, we could add a reference from the integrations page to the Extension section. 

- The extensions section should point to the `Getting Started with Extensions tutorial`. Atm,  the tutorial is https://k6.io/blog/extending-k6-with-xk6/

**Comment by simskij** [comment]
> we should remove the current Extensions section on the Integrations page. Optionally, we could add a reference from the integrations page to the Extension section.

I agree. I suggest we change the copy of the `k6 Extensions` section of the `Integration` page, and add some links.

> Use k6 extensions to further extend the possible use cases of k6. Extensions are written in go and then made available as JavaScript modules for you to utilise in your test scripts.

A button or similar pointing to the ecosystem discovery page:
> Explore the growing ecosystem of k6 extensions

A button or similar pointing to the ecosystem tutorial blog post:
> Learn how to create your own k6 extensions

**Comment by vi-nastya** [comment]
Thanks @simskij! I'll do the changes.
Maybe we could also mention the tutorial in the bundle builder page description, what do you think?

**Comment by simskij** [comment]
Definitely! Good idea! 👏

**Comment by simskij** [comment]
Great work on this, @vi-nastya! I'll go ahead and merge this so we get it into staging for some more testing. Will get back to you if I find anything else that needs to be changed.

**Pull request merged**
