### PR TITLE
[fix] Update test builder docs.

### PR DESCRIPTION
**Pull request by legander**
**NOTE to reviewer:** New Test Builder is still not merged to production (only staging).

Update test builder docs.
Screenshots look blurry, need higher res screenshots.

### CODE REVIEW

**Comment by ppcano** [comment]
LGTM @legander

**Comment by legander** [comment]
Thank you @ppcano 🙏  I'll merge and create a release as soon as the new Test builder is in prod.

**Review by simskij — APPROVED** [review]

**Review by EdvinasDaugirdas — APPROVED** [review]
:rocket:

**Comment by legander** [comment]
I have updated the screenshots, here is the link to the page https://mdr-ci.staging.k6.io/docs/refs/pull/350/merge/test-authoring/test-builder/

**Pull request merged**
